insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (1, 3, 'Energy', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (2, 3, 'Finance', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (3, 1, 'Basic Industries', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (4, 4, 'Capital Goods', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (5, 3, 'Health Care', '2023-02-06');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (6, 4, 'Health Care', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (7, 2, 'Consumer Durables', '2023-02-16');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (8, 2, 'Miscellaneous', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (9, 1, 'Finance', '2023-02-12');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (10, 4, 'Consumer Non-Durables', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (11, 1, 'n/a', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (12, 1, 'Consumer Services', '2023-02-11');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (13, 4, 'Finance', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (14, 1, 'n/a', '2023-02-06');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (15, 4, 'n/a', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (16, 3, 'Health Care', '2023-02-14');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (17, 4, 'Technology', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (18, 3, 'Finance', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (19, 2, 'Finance', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (20, 4, 'Consumer Durables', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (21, 4, 'Consumer Services', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (22, 2, 'Miscellaneous', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (23, 3, 'Capital Goods', '2023-02-11');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (24, 4, 'Health Care', '2023-02-14');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (25, 2, 'Consumer Services', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (26, 3, 'n/a', '2023-02-12');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (27, 1, 'Finance', '2023-02-06');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (28, 4, 'n/a', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (29, 3, 'Health Care', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (30, 3, 'Consumer Services', '2023-02-08');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (31, 4, 'n/a', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (32, 1, 'Health Care', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (33, 2, 'n/a', '2023-02-11');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (34, 2, 'Energy', '2023-02-08');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (35, 3, 'Health Care', '2023-02-06');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (36, 1, 'n/a', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (37, 2, 'Consumer Services', '2023-02-16');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (38, 2, 'Miscellaneous', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (39, 2, 'Capital Goods', '2023-02-14');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (40, 1, 'Finance', '2023-02-14');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (41, 4, 'Health Care', '2023-02-12');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (42, 3, 'Finance', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (43, 2, 'Capital Goods', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (44, 1, 'n/a', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (45, 2, 'Consumer Services', '2023-02-08');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (46, 4, 'n/a', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (47, 4, 'Technology', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (48, 2, 'Basic Industries', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (49, 1, 'n/a', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (50, 3, 'Health Care', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (51, 3, 'Consumer Services', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (52, 4, 'Consumer Services', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (53, 3, 'Consumer Non-Durables', '2023-02-11');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (54, 1, 'Public Utilities', '2023-02-14');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (55, 3, 'Capital Goods', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (56, 1, 'Finance', '2023-02-10');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (57, 3, 'Consumer Non-Durables', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (58, 4, 'Consumer Services', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (59, 2, 'Health Care', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (60, 2, 'Consumer Services', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (61, 1, 'Consumer Services', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (62, 3, 'Technology', '2023-02-12');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (63, 2, 'Finance', '2023-02-10');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (64, 3, 'n/a', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (65, 1, 'Consumer Durables', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (66, 1, 'Energy', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (67, 2, 'Public Utilities', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (68, 4, 'Finance', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (69, 1, 'Health Care', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (70, 1, 'Finance', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (71, 3, 'Finance', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (72, 2, 'Health Care', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (73, 1, 'n/a', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (74, 3, 'Consumer Durables', '2023-02-11');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (75, 3, 'Consumer Non-Durables', '2023-02-12');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (76, 3, 'Capital Goods', '2023-02-06');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (77, 2, 'Energy', '2023-02-10');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (78, 4, 'n/a', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (79, 2, 'Technology', '2023-02-06');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (80, 1, 'n/a', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (81, 2, 'Finance', '2023-02-16');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (82, 4, 'Capital Goods', '2023-02-13');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (83, 3, 'Capital Goods', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (84, 2, 'n/a', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (85, 1, 'Health Care', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (86, 2, 'Basic Industries', '2023-02-09');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (87, 3, 'Energy', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (88, 3, 'n/a', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (89, 1, 'n/a', '2023-02-08');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (90, 4, 'n/a', '2023-02-08');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (91, 4, 'Public Utilities', '2023-02-10');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (92, 3, 'Capital Goods', '2023-02-11');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (93, 4, 'Health Care', '2023-02-16');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (94, 1, 'Finance', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (95, 1, 'Consumer Services', '2023-02-15');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (96, 2, 'n/a', '2023-02-07');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (97, 1, 'n/a', '2023-02-16');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (98, 4, 'Finance', '2023-02-04');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (99, 3, 'n/a', '2023-02-05');
insert into publicacion (idpublicacion, idarticulo, titulo, fecha) values (100, 1, 'n/a', '2023-02-15');
